### ISSUE TITLE
error when hittin "Offset"

### ISSUE THREAD

**Issue by frederico4d** [CenekStrichel/CendaTools#2]
Hi, I get this error when clicking offset, I set the reference, move the object, then offset and get this.

Im on an armature bone, and it doesnt happen always, it is happening on a file but if I start a new one the addon works well :(

Traceback (most recent call last):
  File "C:\Users\frederico.martins\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\cs_offset_animation.py", line 151, in execute
    ApplyOffset( currentLocation, currentRotation, currentScale, currentQRotation, bonePose )
  File "C:\Users\frederico.martins\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\cs_offset_animation.py", line 249, in ApplyOffset
    OffsetAnimation( locDifference, rotDifference, qRotDifference, sclDifference, bonePose )
  File "C:\Users\frederico.martins\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\cs_offset_animation.py", line 289, in OffsetAnimation
    if( (bonePose.name) == ( str(fcurveDataPath).split("\"")[1] ) ):
IndexError: list index out of range

location: <unknown location>:-1

**Comment by CenekStrichel** [comment]
Hello, can you provide your blend file and what you do step by step. So I can see same error?

**Comment by frederico4d** [comment]
Here it is, I try to do that for the selected hand and it gives the bug.
There is only the rig on the file since I had to clean it it up (work stuff)

[rig_test.zip](https://github.com/CenekStrichel/CendaTools/files/2585290/rig_test.zip)

**Comment by CenekStrichel** [comment]
Problem is with channel "#TOP CharExtras" in animation editor, if you delete it, it works. My script is finding bone with name of this channel. But it is not there, so it crash. I will check what I can do.

**Comment by CenekStrichel** [comment]
I made little fix, let me know if everything is ok.

**Comment by frederico4d** [comment]
Damn!! it works, you are the best!
I'll definitely be using this more through the next days and let you know if something happens!
